In [1]:
import numpy as np


In [2]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [5]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
np.random.rand(5,5)

array([[0.37474191, 0.99280039, 0.54366125, 0.05422836, 0.88541938],
       [0.04160819, 0.9409872 , 0.93739816, 0.85610095, 0.2870793 ],
       [0.50070445, 0.62428545, 0.05532902, 0.24331444, 0.65848665],
       [0.10602283, 0.25660465, 0.12231186, 0.58609847, 0.15354172],
       [0.65366268, 0.94998214, 0.54330369, 0.64348849, 0.19525557]])

In [13]:
np.random.randn(5,5)

array([[ 0.4647601 , -1.81510107,  1.47214193, -0.99689113, -0.00583962],
       [ 0.25071732,  0.32950486,  0.03719742, -0.5459167 ,  1.94136053],
       [ 0.51068104, -0.98706468, -0.87865317, -0.65045012, -0.35428565],
       [-1.87866429, -0.6647583 ,  0.71730689, -1.43690806,  0.64652638],
       [ 0.88578202, -0.44443633,  0.96301134,  0.14083797, -0.89201913]])

In [14]:
mymat = np.arange(25)

In [15]:
mymat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
mymat.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
myarray = np.arange(10,21)

In [18]:
myarray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
myarray[1:4]

array([11, 12, 13])

In [20]:
myarray[:4]

array([10, 11, 12, 13])

In [21]:
myarray[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [22]:
mynew = myarray[:4]

In [23]:
mynew

array([10, 11, 12, 13])

In [24]:
mynew[:] = 100

In [25]:
mynew

array([100, 100, 100, 100])

In [26]:
myarray

array([100, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [27]:
myarr = myarray.copy()

In [28]:
myarr[:] = 50

In [29]:
myarr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [30]:
myarray

array([100, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [31]:
mytwodarray = [[1,2,3],[4,5,6],[7,8,9]]

In [32]:
mytwodarray

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
myTwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
myTwoDArray[ :2 , :2]

array([[1, 2],
       [4, 5]])

In [37]:
narray = np.arange(2,20)

In [38]:
newarray

NameError: name 'newarray' is not defined

In [39]:
narray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [40]:
narray[narray>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
narray * 2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [42]:
narray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [44]:
narray + narray

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [47]:
np.sqrt(narray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])

In [48]:
x = [1,2,3]
y = [4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [49]:
np.dot(3,4)

12

In [50]:
a = [[1,0],[0,1]]

In [51]:
b = [[4,1],[2,2]]

In [52]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [53]:
x = np.arange(4).reshape((2,2))

In [54]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [55]:
x = np.arange(8)

In [56]:
np.array_split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [57]:
a = np.array([[1,2],[3,4]])

In [58]:
np.mean(a)

2.5

In [59]:
np.mean(a,axis=0)

array([2., 3.])

In [60]:
np.mean(a,axis=1)

array([1.5, 3.5])

In [61]:
x = np.array([[0,2],[1,1],[2,6]]).T

In [62]:
x

array([[0, 1, 2],
       [2, 1, 6]])

In [63]:
np.cov(x)

array([[1., 2.],
       [2., 7.]])