In [1]:
pwd

'C:\\Users\\DELL'

In [2]:
import numpy as np

In [3]:
myArray = np.arange(10,21)

In [4]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
myArray[1:6]

array([11, 12, 13, 14, 15])

In [6]:
myArray[:5]

array([10, 11, 12, 13, 14])

In [7]:
myArray[5:]

array([15, 16, 17, 18, 19, 20])

In [8]:
partArray = myArray[:5]

In [9]:
partArray

array([10, 11, 12, 13, 14])

In [10]:
partArray[:] = 50

In [11]:
partArray

array([50, 50, 50, 50, 50])

In [12]:
myArray

array([50, 50, 50, 50, 50, 15, 16, 17, 18, 19, 20])

In [13]:
copyArray = myArray.copy()

In [14]:
copyArray

array([50, 50, 50, 50, 50, 15, 16, 17, 18, 19, 20])

In [15]:
copyArray[:] = 100

In [16]:
copyArray

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
myArray

array([50, 50, 50, 50, 50, 15, 16, 17, 18, 19, 20])

In [18]:
myTwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
myTwoDArray[2][1]

8

In [21]:
myTwoDArray[2,1]

8

In [22]:
myTwoDArray[2]

array([7, 8, 9])

In [23]:
myTwoDArray[:2,1:]

array([[2, 3],
       [5, 6]])

In [24]:
myTwoDArray[:2,:2]

array([[1, 2],
       [4, 5]])

In [25]:
myTwoDArray[1:,:2]

array([[4, 5],
       [7, 8]])

In [26]:
myTwoDArray[1:,1:]

array([[5, 6],
       [8, 9]])

In [28]:
newArray = np.arange(1,21)

In [29]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
newArray[newArray>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
newArray[newArray<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
newArray>11

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
newArray


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
np.sqrt(newArray)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [35]:
x=[1,2,3]
y=[4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [36]:
np.dot(3,4)

12

In [37]:
np.dot(x,y)

32