#exercise files for numpy


In [1]:
myList = [1,2,3,4,5]


In [2]:
myList


[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [5]:
myonedarray = np.array(myList)

In [7]:
mymultilist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]


In [8]:
mytwodarray = np.array(mymultilist)

In [9]:
mytwodarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.zeros(4)


array([0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [18]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5,5)

array([[0.63152296, 0.17310669, 0.24441104, 0.88500807, 0.44565084],
       [0.95824727, 0.18450065, 0.95028222, 0.25468674, 0.1284848 ],
       [0.87856364, 0.52913426, 0.9161727 , 0.16520607, 0.66736647],
       [0.56145261, 0.81697911, 0.10977862, 0.48995735, 0.32307803],
       [0.2322204 , 0.21864502, 0.88466712, 0.06376139, 0.84751787]])

In [20]:
np.random.randn(5,5)

array([[ 0.34317642,  0.28130036, -0.55784453, -1.23335491,  0.55478503],
       [-0.13907204,  0.12901604, -1.15328146, -0.5922705 ,  0.66337391],
       [ 0.47597838, -0.32853933,  0.98335635, -0.06673719,  0.18743203],
       [-1.21631059,  0.09615762,  1.7936928 ,  0.53338529, -0.04515877],
       [ 1.79135911,  0.49198411,  1.67548005,  0.6118671 , -0.66279088]])

In [25]:
np.random.randint(0,50)

7

In [26]:
mynum = np.arange(25)

In [27]:
mynum


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
myreshape = mynum.reshape(5,5)

In [2]:
pwd

'C:\\Users\\DELL'